sudo: false
language: python
notifications:
  email: false
python:
  - pypy
  - 2.6
  - 2.7
  - 3.3
  - 3.4
  - 3.5
matrix:
  include:
    - python: 2.7
      dist: trusty
      sudo: required
      virtualenv:
        system_site_packages: true
      addons:
        apt:
          sources:
            - debian-sid  # lxml 3.6.0
          packages:
            - python-requests
            - python-sqlalchemy
            - python-xlwt
            - python-xlrd
            - python-lxml
            - python-openpyxl
            - python-flask
            - python-coverage
            - python-nose
            - python-mock
            - python-wheel
before_install:
  - if [[ $TRAVIS_PYTHON_VERSION == "pypy" || $TRAVIS_PYTHON_VERSION == "pypy3" ]]; then rm tests/test_examples.py; fi
  - if [[ -f rnd_requirements.txt ]]; then
      pip install --upgrade "setuptools==17.1" "pip==7.1" ;
      pip install -r rnd_requirements.txt ;
    fi
  - pip install -r tests/requirements.txt
script:
  make test
after_success:
  codecov
