
sudo: false
dist: xenial
language: python
notifications:
  email: false
python:
  - &pypy2 pypy2.7-6.0
  - &pypy3 pypy3.5-6.0
  - 3.8-dev
  - 3.7
  - 3.6
  - 3.5
  - 2.7
matrix:
  include:
    - python: 2.7
      env: MINREQ=1

stages:
  - test
  - lint

.disable_global: &disable_global
  before_install: false
  install: true
  before_script: false
  after_success: false
  after_failure: false

.lint: &lint
  <<: *disable_global
  python: 3.6
  stage: lint
  install: pip install flake8
  script: make lint

jobs:
  include:
    - *lint

stage: test

script: make test

before_install:
  - if [[ $TRAVIS_PYTHON_VERSION == "pypy" ]]; then rm tests/test_examples.py; fi
  - if [[ -f min_requirements.txt && "$MINREQ" -eq 1 ]]; then
      mv min_requirements.txt requirements.txt ;
    fi
  - test ! -f rnd_requirements.txt || pip install --no-deps -r rnd_requirements.txt
  - test ! -f rnd_requirements.txt || pip install -r rnd_requirements.txt ;
  - pip install -r tests/requirements.txt
script:
  - make test
after_success:
  codecov
