on: [push]

jobs:
  run_moban:
    runs-on: ubuntu-latest
    name: synchronize templates via moban
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.PAT }}
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.7'
      - name: install dependencies
        run: |
          pip install moban gitfs2 pypifs moban-jinja2-github moban-ansible
          moban
          git status
      - name: check changes
        if: failure()
        run: Exit
        if: success()
        run: |
          git diff --exit-code
      - name: Auto-commit
        if: failure()
        uses: docker://cdssnc/auto-commit-github-action
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: >-
            This is an auto-commit, updating project meta data,
            such as changelog.rst, contributors.rst
      - name: Exit
        run: echo "I am done"
